#!/usr/bin/env python3
"""
SOC-ify Daily Report Generator
==============================
Compiles a concise daily SOC summary from `siem-findings` + `nginx-access-*`
and emits markdown (and optional HTML). Designed to be run by cron / Task Scheduler.

Output goes to `reports/soc_daily_YYYY-MM-DD.md` (and .html if --html).

USAGE:
  python daily_report.py --days 1 --format md
  python daily_report.py --days 1 --html  --notify slack   # via webhook (optional)

Deliverables: stats, top attack classes, top IPs, top paths, open cases, and a
plain-text MTTD style summary. Wrapped so it can be pasted into Telegram/Slack.
"""
import argparse, collections, datetime, json, os, sys

try:
    from elasticsearch import Elasticsearch
except ImportError:
    sys.exit("[!] pip install elasticsearch")

ES_HOST = os.environ.get("SOC_ES_HOST", "http://localhost:9200")
ES_USER = os.environ.get("SOC_ES_USER", "CHANGE_ME")
ES_PASS = os.environ.get("SOC_ES_PASS", "CHANGE_ME")
FINDINGS = os.environ.get("SOC_FINDINGS", "siem-findings")
NGINX = os.environ.get("SOC_INDEX", "nginx-access-*")
REPORT_DIR = os.path.join(os.path.dirname(__file__), "..", "reports")
os.makedirs(REPORT_DIR, exist_ok=True)


def es():
    return Elasticsearch([ES_HOST], basic_auth=(ES_USER, ES_PASS),
                         request_timeout=30, verify_certs=False)


def today_str():
    return datetime.date.today().isoformat()


def top_terms(es, index, field, rng, size=10):
    body = {
        "size": 0,
        "query": {"range": {"@timestamp": {"gte": rng}}},
        "aggs": {field.replace(".", "_"): {"terms": {"field": field, "size": size}}},
    }
    try:
        agg = es.search(index=index, body=body)["aggregations"]
        k = field.replace(".", "_")
        return [(b["key"], b["doc_count"]) for b in agg[k]["buckets"]]
    except Exception:
        return []


def metric(es, index, rng, body=None):
    body = body or {"size": 0, "query": {"range": {"@timestamp": {"gte": rng}}}}
    try:
        return es.search(index=index, body=body)["hits"]["total"]["value"]
    except Exception:
        return 0


def find_open_cases(es, rng):
    body = {
        "size": 50,
        "query": {"bool": {"filter": [
            {"range": {"@timestamp": {"gte": rng}}},
            {"term": {"status": "open"}},
        ]}},
        "sort": [{"severity": "desc"}],
    }
    try:
        return es.search(index=FINDINGS, body=body)["hits"]["hits"]
    except Exception:
        return []


def build_md(es, days):
    rng = f"now-{days}d"
    lines = []
    lines.append(f"# SOC Daily Report — {today_str()}")
    lines.append(f"Scope: last {days}d of {NGINX}\n")

    total = metric(es, NGINX, rng)
    errs_4 = metric(es, NGINX, rng, {"size": 0, "query": {"bool": {"filter": [
        {"range": {"@timestamp": {"gte": rng}}},
        {"range": {"http.response.status_code": {"gte": 400, "lt": 500}}},

    ]}}})
    errs_5 = metric(es, NGINX, rng, {"size": 0, "query": {"bool": {"filter": [
        {"range": {"@timestamp": {"gte": rng}}},
        {"range": {"http.response.status_code": {"gte": 500}}},
    ]}}})
    findings_n = metric(es, FINDINGS, rng)
    open_n = len([c for c in find_open_cases(es, rng) if c["_source"].get("status") == "open"])

    lines.append("## Key Metrics")
    lines.append(f"- Total requests: **{total}**")
    lines.append(f"- 4xx: **{errs_4}** | 5xx: **{errs_5}**")
    lines.append(f"- Findings generated: **{findings_n}** | still open: **{open_n}**\n")

    lines.append("## Top Attack Classes")
    for k, v in top_terms(es, NGINX, "soc.attack_class", rng):
        lines.append(f"- {k}: {v}")
    lines.append("")

    lines.append("## Top Source IPs")
    for k, v in top_terms(es, NGINX, "client.ip", rng):
        lines.append(f"- `{k}`: {v}")
    lines.append("")

    lines.append("## Top Probe Paths")
    for k, v in top_terms(es, NGINX, "url.path", rng):
        lines.append(f"- `{k}`: {v}")
    lines.append("")

    lines.append("## Findings by Rule")
    for k, v in top_terms(es, FINDINGS, "rule_id", rng):
        lines.append(f"- {k}: {v}")
    lines.append("")

    lines.append("## Open Cases (priority)")
    cases = [c for c in find_open_cases(es, rng) if c["_source"].get("status") == "open"]
    if not cases:
        lines.append("- (none)")
    for c in cases[:15]:
        s = c["_source"]
        lines.append(f"- [{s.get('severity')}] {s.get('rule_id')} {s.get('rule_title')} "
                     f"ip={s.get('client.ip')} {s.get('url.path')}")
    lines.append("")

    lines.append("---")
    lines.append("*Generated by SOC-ify daily_report.py — route to Slack/Telegram/email.*")
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--days", type=int, default=1)
    ap.add_argument("--html", action="store_true", help="also emit HTML")
    a = ap.parse_args()

    client = es()
    if not client.ping():
        sys.exit("[!] ES unreachable")

    md = build_md(client, a.days)
    md_path = os.path.join(REPORT_DIR, f"soc_daily_{today_str()}.md")
    with open(md_path, "w", encoding="utf-8") as f:
        f.write(md)
    print(md)
    print(f"\n[*] written: {os.path.abspath(md_path)}")

    if a.html:
        html = f"<html><body><pre>{md}</pre></body></html>"
        hp = os.path.join(REPORT_DIR, f"soc_daily_{today_str()}.html")
        with open(hp, "w", encoding="utf-8") as f:
            f.write(html)
        print(f"[*] written: {os.path.abspath(hp)}")


if __name__ == "__main__":
    main()
